name: generate
on:
  pull_request:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execute tbls-spanner
        uses: lirlia/tbls-spanner@v1
        with:
          ddl_path: './spanner.sql'
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}